[package]
name = "dex-parser"
version = "0.1.0"
authors = ["Rohit Kumar <letmutx@gmail.com>"]
edition = "2018"

[dependencies]
cesu8 = "1.1.0"
scroll = "0.9.0"
scroll_derive = "0.9.2"
memmap = "0.7.0"
lru = "0.1.13"
num-traits = "0.2"
num-derive = "0.2"
